site_name: E-paper panel
site_url: https://jakubandrysek.github.io/E-paper-board-ESP32/
site_author: Jakub Andrýsek
site_description: >-
  Create a branded static site from a set of Markdown files to host the
  documentation of your Open Source or commercial project
# Repository
repo_name: JakubAndrysek/E-paper-board-ESP32
repo_url: https://github.com/JakubAndrysek/E-paper-board-ESP32
edit_uri: blob/main/docs/

# Copyright
copyright: Copyright &copy; 2022 Jakub Andrýsek

theme:
  name: material
  language: cs
  # logo: assets/logo.png
  # favicon: images/favicon.png
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top

  icon:
    repo: fontawesome/brands/github

  palette:
    - scheme: default
      primary: light blue
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Přepnout na tmavý režim
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Přepnout na světý režim

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/JakubAndrysek
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Jakubandrysek1
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jakub-andrysek/
  # consent:
  #   title: Cookie consent
  #   description: >-
  #     We use cookies to recognize your repeated visits and preferences, as well
  #     as to measure the effectiveness of our documentation and whether users
  #     find what they're searching for. With your consent, you're helping us to
  #     make our documentation better.
  #   analytics:
  #     name: Google Analytics
  #     checked: false

use_directory_urls: True

plugins:
  - search
  - awesome-pages # https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin
  - mkdoxy: # https://github.com/JakubAndrysek/mkdoxy
      projects:
        api-board:
          src-dirs: sw/e-paper-board/src/
          full-doc: True
          doxy-cfg:
            FILE_PATTERNS: "*.c* *.h*"
            # EXAMPLE_PATH: examples
            RECURSIVE: True

      save-api: .mkdoxy
      full-doc: True
      debug: False
      ignore-errors: False

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - "Domů": "index.md"
  - ... | aplikace/**.md
  - ... | panel/**.md
  - ... | server/**.md
  - API Panelu:
      - api-board/index.md
      - "Links": "api-board/links.md"
      - "Classes":
          - "Class List": "api-board/annotated.md"
          - "Class Index": "api-board/classes.md"
          - "Class Hierarchy": "api-board/hierarchy.md"
          - "Class Members": "api-board/class_members.md"
          - "Class Member Functions": "api-board/class_member_functions.md"
          - "Class Member Variables": "api-board/class_member_variables.md"
          - "Class Member Typedefs": "api-board/class_member_typedefs.md"
          - "Class Member Enumerations": "api-board/class_member_enums.md"
      - "Namespaces":
          - "Namespace List": "api-board/namespaces.md"
          - "Namespace Members": "api-board/namespace_members.md"
          - "Namespace Member Functions": "api-board/namespace_member_functions.md"
          - "Namespace Member Variables": "api-board/namespace_member_variables.md"
          - "Namespace Member Typedefs": "api-board/namespace_member_typedefs.md"
          - "Namespace Member Enumerations": "api-board/namespace_member_enums.md"
      - "Functions": "api-board/functions.md"
      - "Variables": "api-board/variables.md"
      - "Macros": "api-board/macros.md"
      - "Files": "api-board/files.md"
