docs_dir: docs
site_name: E-paper panel
site_url: https://jakubandrysek.github.io/E-paper-board-ESP32/
site_author: Jakub Andrýsek
site_description: >-
  Cílem tohoto projektu je navrhnout a vytvořit univerzální domácí panel. 
  Hlavním úkolem tohoto panelu je zobrazovat aktuální odjezdy městské hromadné dopravy.

# Repository
repo_name: JakubAndrysek/E-paper-board-ESP32
repo_url: https://github.com/JakubAndrysek/E-paper-board-ESP32
edit_uri: blob/main/docs/

# Copyright
copyright: Copyright &copy; 2022 Jakub Andrýsek

theme:
  name: material
  language: cs
  # logo: assets/logo.png
  # favicon: images/favicon.png
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top

  icon:
    repo: fontawesome/brands/github

  palette:
    - scheme: default
      primary: light blue
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Přepnout na tmavý režim
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Přepnout na světý režim

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/JakubAndrysek
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Jakubandrysek1
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jakub-andrysek/
  # consent:
  #   title: Cookie consent
  #   description: >-
  #     We use cookies to recognize your repeated visits and preferences, as well
  #     as to measure the effectiveness of our documentation and whether users
  #     find what they're searching for. With your consent, you're helping us to
  #     make our documentation better.
  #   analytics:
  #     name: Google Analytics
  #     checked: false

use_directory_urls: True

plugins:
  - search
  - mkdoxy: # https://github.com/JakubAndrysek/mkdoxy
      projects:
        api-board:
          src-dirs: sw/e-paper-board/src/
          full-doc: True
          doxy-cfg:
            FILE_PATTERNS: "*.c* *.h*"
            EXAMPLE_PATH: ""
            RECURSIVE: True
        api-server:
          src-dirs: sw/server/python-wrapper/
          full-doc: True
          doxy-cfg:
            FILE_PATTERNS: "*.py"
            EXAMPLE_PATH: ""
            RECURSIVE: True
            OPTIMIZE_OUTPUT_JAVA: True
            JAVADOC_AUTOBRIEF: True
            EXTRACT_ALL: True

      save-api: .mkdoxy
      full-doc: True
      # full-doc: False
      debug: False
      ignore-errors: False

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - featherlight # install:

extra_javascript:
  - vendor/jquery-latest.js #https://code.jquery.com/jquery-latest.js
  - vendor/featherlight.min.js # https://cdn.jsdelivr.net/npm/featherlight@1.7.14/release/featherlight.min.js

extra_css:
  - vendor/featherlight.min.css #https://cdn.jsdelivr.net/npm/featherlight@1.7.14/release/featherlight.min.css

nav:
  - "Domů": "index.md"
  - Panel:
      - panel/index.md
      - panel/vstup.md
      - panel/jadro.md
      - panel/vykreslovani.md
      - panel/testovani.md
  - Aplikace:
      - aplikace/index.md
      - aplikace/mhd.md
      - aplikace/alojz.md
      - aplikace/sol-znamky.md
      - aplikace/sol-rozvrh.md
      - aplikace/fablab.md
  - Wrapper:
      - wrapper/index.md
      - wrapper/mhd.md
      - wrapper/alojz.md
      - wrapper/sol-znamky.md
      - wrapper/sol-rozvrh.md
      - wrapper/fablab.md
  - API dokumentace:
      - api/index.md
      - API Panelu:
          - api-board/index.md
          - "Links": "api-board/links.md"
          - "Classes":
              - "Class List": "api-board/annotated.md"
              - "Class Index": "api-board/classes.md"
              - "Class Hierarchy": "api-board/hierarchy.md"
              - "Class Members": "api-board/class_members.md"
              - "Class Member Functions": "api-board/class_member_functions.md"
              - "Class Member Variables": "api-board/class_member_variables.md"
              - "Class Member Typedefs": "api-board/class_member_typedefs.md"
              - "Class Member Enumerations": "api-board/class_member_enums.md"
          - "Namespaces":
              - "Namespace List": "api-board/namespaces.md"
              - "Namespace Members": "api-board/namespace_members.md"
              - "Namespace Member Functions": "api-board/namespace_member_functions.md"
              - "Namespace Member Variables": "api-board/namespace_member_variables.md"
              - "Namespace Member Typedefs": "api-board/namespace_member_typedefs.md"
              - "Namespace Member Enumerations": "api-board/namespace_member_enums.md"
          - "Functions": "api-board/functions.md"
          - "Variables": "api-board/variables.md"
          - "Macros": "api-board/macros.md"
          - "Files": "api-board/files.md"
      - API Serveru:
          - api-server/index.md
          - "Links": "api-server/links.md"
          - "Classes":
              - "Class List": "api-server/annotated.md"
              - "Class Index": "api-server/classes.md"
              - "Class Hierarchy": "api-server/hierarchy.md"
              - "Class Members": "api-server/class_members.md"
              - "Class Member Functions": "api-server/class_member_functions.md"
              - "Class Member Variables": "api-server/class_member_variables.md"
              - "Class Member Typedefs": "api-server/class_member_typedefs.md"
              - "Class Member Enumerations": "api-server/class_member_enums.md"
          - "Namespaces":
              - "Namespace List": "api-server/namespaces.md"
              - "Namespace Members": "api-server/namespace_members.md"
              - "Namespace Member Functions": "api-server/namespace_member_functions.md"
              - "Namespace Member Variables": "api-server/namespace_member_variables.md"
              - "Namespace Member Typedefs": "api-server/namespace_member_typedefs.md"
              - "Namespace Member Enumerations": "api-server/namespace_member_enums.md"
          - "Functions": "api-server/functions.md"
          - "Variables": "api-server/variables.md"
          - "Macros": "api-server/macros.md"
          - "Files": "api-server/files.md"
