docs_dir: docs
site_name: E-paper panel
site_url: https://jakubandrysek.github.io/E-paper-board-ESP32/
site_author: Jakub Andrýsek
site_description: >-
  The aim of this project is to design and create a universal home panel.
  The main task of this panel is to display the current departures of public transport.


# Repository
repo_name: JakubAndrysek/E-paper-board-ESP32
repo_url: https://github.com/JakubAndrysek/E-paper-board-ESP32
# edit_uri: blob/main/docs/
# edit_uri: ""

# Copyright
copyright: Copyright © 2023 Jakub Andrýsek

theme:
  name: material
  language: cs
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top

  icon:
    repo: fontawesome/brands/github

  palette:
    - scheme: slate
      primary: red
      accent: red


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/JakubAndrysek
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/KubaAndrysek
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jakub-andrysek/
  analytics:
    provider: google
    property: G-21J1TXRYM8

use_directory_urls: True

plugins:
  # - with-pdf # https://github.com/orzih/mkdocs-with-pdf
  # - mkpdfs: # install: pip install https://github.com/dirks/mkpdfs-mkdocs-plugin/archive/e73e8a3e430325b9bd4df0e98d94237439cb99a9.zip
  #     design: docs/vendor/mkpdfs-design-sample/report.css
  - search
  - glightbox
  # - i18n:
  #   default_language: !ENV [DEFAULT_LANGUAGE, "en"]
  #   default_language_only: !ENV [DEFAULT_LANGUAGE_ONLY, false]
  #   docs_structure: suffix
  #   languages:
  #     default:
  #       name: Default (en)
  #       build: true
  #     cs:
  #       name: Czech (cs)
  #       build: true
  #       site_name: InkSvgNest
  #   # nav_translations:
  #   #   fr:
  #   #     Topic1: Sujet1
  #   #     Topic2: Sujet2
  - mkdoxy: # https://github.com/JakubAndrysek/mkdoxy
      projects:
        apiBoard:
          src-dirs: sw/e-paper-board/src/
          full-doc: True
          doxy-cfg:
            FILE_PATTERNS: "*.c* *.h*"
            EXAMPLE_PATH: ""
            RECURSIVE: True
        apiWrapper:
          src-dirs: sw/python-wrapper/
          full-doc: True
          doxy-cfg:
            FILE_PATTERNS: "*.py"
            EXAMPLE_PATH: ""
            RECURSIVE: True
            OPTIMIZE_OUTPUT_JAVA: True
            JAVADOC_AUTOBRIEF: True
            EXTRACT_ALL: True

      save-api: .mkdoxy
      full-doc: True
      # full-doc: False
      debug: False
      ignore-errors: False

  # - git-revision-date-localized

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true


nav:
  - Domů:
    - "index.md"
    - technologie.md
  - Panel:
      - panel/index.md
      - panel/vstup.md
      - panel/jadro.md
      - panel/vykreslovani.md
  - Aplikace:
      - aplikace/index.md
      - aplikace/mhd.md
      - aplikace/alojz.md
      - aplikace/sol-znamky.md
      - aplikace/sol-rozvrh.md
      - aplikace/fablab.md
  - Wrapper:
      - wrapper/index.md
      - wrapper/mhd.md
      - wrapper/alojz.md
      - wrapper/sol-znamky.md
      - wrapper/sol-rozvrh.md
      - wrapper/fablab.md
  - API dokumentace:
      - api/index.md
      - API Panelu:
          - apiBoard/index.md
          - "Links": "apiBoard/links.md"
          - "Classes":
              - "Class List": "apiBoard/annotated.md"
              - "Class Index": "apiBoard/classes.md"
              - "Class Hierarchy": "apiBoard/hierarchy.md"
              - "Class Members": "apiBoard/class_members.md"
              - "Class Member Functions": "apiBoard/class_member_functions.md"
              - "Class Member Variables": "apiBoard/class_member_variables.md"
              - "Class Member Typedefs": "apiBoard/class_member_typedefs.md"
              - "Class Member Enumerations": "apiBoard/class_member_enums.md"
          - "Namespaces":
              - "Namespace List": "apiBoard/namespaces.md"
              - "Namespace Members": "apiBoard/namespace_members.md"
              - "Namespace Member Functions": "apiBoard/namespace_member_functions.md"
              - "Namespace Member Variables": "apiBoard/namespace_member_variables.md"
              - "Namespace Member Typedefs": "apiBoard/namespace_member_typedefs.md"
              - "Namespace Member Enumerations": "apiBoard/namespace_member_enums.md"
          - "Functions": "apiBoard/functions.md"
          - "Variables": "apiBoard/variables.md"
          - "Macros": "apiBoard/macros.md"
          - "Files": "apiBoard/files.md"
      - API Wrapper:
          - apiWrapper/index.md
          - "Links": "apiWrapper/links.md"
          - "Classes":
              - "Class List": "apiWrapper/annotated.md"
              - "Class Index": "apiWrapper/classes.md"
              - "Class Hierarchy": "apiWrapper/hierarchy.md"
              - "Class Members": "apiWrapper/class_members.md"
              - "Class Member Functions": "apiWrapper/class_member_functions.md"
              - "Class Member Variables": "apiWrapper/class_member_variables.md"
              - "Class Member Typedefs": "apiWrapper/class_member_typedefs.md"
              - "Class Member Enumerations": "apiWrapper/class_member_enums.md"
          - "Namespaces":
              - "Namespace List": "apiWrapper/namespaces.md"
              - "Namespace Members": "apiWrapper/namespace_members.md"
              - "Namespace Member Functions": "apiWrapper/namespace_member_functions.md"
              - "Namespace Member Variables": "apiWrapper/namespace_member_variables.md"
              - "Namespace Member Typedefs": "apiWrapper/namespace_member_typedefs.md"
              - "Namespace Member Enumerations": "apiWrapper/namespace_member_enums.md"
          - "Functions": "apiWrapper/functions.md"
          - "Variables": "apiWrapper/variables.md"
          - "Macros": "apiWrapper/macros.md"
          - "Files": "apiWrapper/files.md"
  - Závěr:
      - zaver/index.md