docs_dir: docs
site_name: E-paper panel
site_url: https://jakubandrysek.github.io/E-paper-board-ESP32/
site_author: Jakub Andrýsek
site_description: >-
  Cílem tohoto projektu je navrhnout a vytvořit univerzální domácí panel.
  Hlavním úkolem tohoto panelu je zobrazovat aktuální odjezdy městské hromadné dopravy.

# Repository
repo_name: JakubAndrysek/E-paper-board-ESP32
repo_url: https://github.com/JakubAndrysek/E-paper-board-ESP32
# edit_uri: blob/main/docs/
edit_uri: ""

# Copyright
copyright: Copyright © 2022 Jakub Andrýsek

theme:
  name: material
  language: cs
  # logo: assets/logo.png
  # favicon: images/favicon.png
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top

  icon:
    repo: fontawesome/brands/github

  palette:
    - scheme: default
      primary: light blue
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Přepnout na tmavý režim
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Přepnout na světý režim

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/JakubAndrysek
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/KubaAndrysek
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jakub-andrysek/
  analytics:
    provider: google
    property: G-21J1TXRYM8

use_directory_urls: True

plugins:
  # - with-pdf # https://github.com/orzih/mkdocs-with-pdf
  # - mkpdfs: # install: pip install https://github.com/dirks/mkpdfs-mkdocs-plugin/archive/e73e8a3e430325b9bd4df0e98d94237439cb99a9.zip
  #     design: docs/vendor/mkpdfs-design-sample/report.css
  - search
  - mkdoxy: # https://github.com/JakubAndrysek/mkdoxy
      projects:
        apiBoard:
          src-dirs: sw/e-paper-board/src/
          full-doc: True
          doxy-cfg:
            FILE_PATTERNS: "*.c* *.h*"
            EXAMPLE_PATH: ""
            RECURSIVE: True
        apiWrapper:
          src-dirs: sw/python-wrapper/
          full-doc: True
          doxy-cfg:
            FILE_PATTERNS: "*.py"
            EXAMPLE_PATH: ""
            RECURSIVE: True
            OPTIMIZE_OUTPUT_JAVA: True
            JAVADOC_AUTOBRIEF: True
            EXTRACT_ALL: True

      save-api: .mkdoxy
      full-doc: True
      # full-doc: False
      debug: False
      ignore-errors: False

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - featherlight # install: pip install git+https://github.com/it-novum/mkdocs-featherlight.git

extra_javascript:
  - vendor/jquery-latest.js #https://code.jquery.com/jquery-latest.js
  - vendor/featherlight.min.js # https://cdn.jsdelivr.net/npm/featherlight@1.7.14/release/featherlight.min.js

extra_css:
  - vendor/featherlight.min.css #https://cdn.jsdelivr.net/npm/featherlight@1.7.14/release/featherlight.min.css

nav:
  - Domů:
    - "index.md"
    - technologie.md
  - Panel:
      - panel/index.md
      - panel/vstup.md
      - panel/jadro.md
      - panel/vykreslovani.md
  - Aplikace:
      - aplikace/index.md
      - aplikace/mhd.md
      - aplikace/alojz.md
      - aplikace/sol-znamky.md
      - aplikace/sol-rozvrh.md
      - aplikace/fablab.md
  - Wrapper:
      - wrapper/index.md
      - wrapper/mhd.md
      - wrapper/alojz.md
      - wrapper/sol-znamky.md
      - wrapper/sol-rozvrh.md
      - wrapper/fablab.md
  - API dokumentace:
      - api/index.md
      - API Panelu:
          - apiBoard/index.md
          - "Links": "apiBoard/links.md"
          - "Classes":
              - "Class List": "apiBoard/annotated.md"
              - "Class Index": "apiBoard/classes.md"
              - "Class Hierarchy": "apiBoard/hierarchy.md"
              - "Class Members": "apiBoard/class_members.md"
              - "Class Member Functions": "apiBoard/class_member_functions.md"
              - "Class Member Variables": "apiBoard/class_member_variables.md"
              - "Class Member Typedefs": "apiBoard/class_member_typedefs.md"
              - "Class Member Enumerations": "apiBoard/class_member_enums.md"
          - "Namespaces":
              - "Namespace List": "apiBoard/namespaces.md"
              - "Namespace Members": "apiBoard/namespace_members.md"
              - "Namespace Member Functions": "apiBoard/namespace_member_functions.md"
              - "Namespace Member Variables": "apiBoard/namespace_member_variables.md"
              - "Namespace Member Typedefs": "apiBoard/namespace_member_typedefs.md"
              - "Namespace Member Enumerations": "apiBoard/namespace_member_enums.md"
          - "Functions": "apiBoard/functions.md"
          - "Variables": "apiBoard/variables.md"
          - "Macros": "apiBoard/macros.md"
          - "Files": "apiBoard/files.md"
      - API Wrapper:
          - apiWrapper/index.md
          - "Links": "apiWrapper/links.md"
          - "Classes":
              - "Class List": "apiWrapper/annotated.md"
              - "Class Index": "apiWrapper/classes.md"
              - "Class Hierarchy": "apiWrapper/hierarchy.md"
              - "Class Members": "apiWrapper/class_members.md"
              - "Class Member Functions": "apiWrapper/class_member_functions.md"
              - "Class Member Variables": "apiWrapper/class_member_variables.md"
              - "Class Member Typedefs": "apiWrapper/class_member_typedefs.md"
              - "Class Member Enumerations": "apiWrapper/class_member_enums.md"
          - "Namespaces":
              - "Namespace List": "apiWrapper/namespaces.md"
              - "Namespace Members": "apiWrapper/namespace_members.md"
              - "Namespace Member Functions": "apiWrapper/namespace_member_functions.md"
              - "Namespace Member Variables": "apiWrapper/namespace_member_variables.md"
              - "Namespace Member Typedefs": "apiWrapper/namespace_member_typedefs.md"
              - "Namespace Member Enumerations": "apiWrapper/namespace_member_enums.md"
          - "Functions": "apiWrapper/functions.md"
          - "Variables": "apiWrapper/variables.md"
          - "Macros": "apiWrapper/macros.md"
          - "Files": "apiWrapper/files.md"
  - Závěr:
      - zaver/index.md