installů:
	npm install -g json-server

serve-departures:
	json-server --watch --host 192.168.0.15 --port 3333 departures.json

serve-departures-robotarna:
	# json-server --watch --host 192.168.42.22 --port 3333 departures.json
	json-server --watch --host 192.168.42.22 --port 3333 departures.json