install:
	npm install -g json-server

serve-departures-pletacka:
	json-server --watch --host 192.168.0.15 --port 3333 test-data.json

serve-departures-rotex:
	json-server --watch --host 192.168.0.5 --port 3333 test-data.json

serve-departures-robotarna:
	json-server --watch --host 192.168.42.22 --port 3333 test-data.json