name: ci
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: sudo apt install doxygen
      - run: pip install mkdocs-material
      - run: pip install git+https://github.com/JakubAndrysek/mkdoxy.git
      - run: pip install git+https://github.com/it-novum/mkdocs-featherlight.git
      - run: pip install mkpdfs-mkdocs
      - run: pip install mkdocs-awesome-pages-plugin

      # - run: apt install python3-pip python3-cffi python3-brotli libpango-1.0-0 libharfbuzz0b libpangoft2-1.0-0
      # - run: pip install weasyprint
      # - run: pip install git+https://github.com/dirks/mkpdfs-mkdocs-plugin/archive/e73e8a3e430325b9bd4df0e98d94237439cb99a9.zip
      # - run: pip install mkdocs-with-pdf

      - run: mkdocs gh-deploy --force